### ISSUE TITLE
.full width glyphs are not full width

### ISSUE THREAD

**Issue by aaronbell** [satsuyako/CherryBomb#8]
The font contains a set of Latin `.full` glyphs, but none are full width. Given that the Kana included in the font are proportional as well, are these full width forms necessary?

**Comment by satsuyako** [comment]
I think latin .full forms are necessary when typing Japanese consonant letters.
There seems to be a problem with the Japanese font not included full width forms.
[https://twitter.com/toriaka/status/1199305161811738625?s=20](url)

**Comment by aaronbell** [comment]
Oh interesting. It appears that certain Japanese IMEs default to point to the full width forms (maybe under certain conditions?). OK, I'll make the fullwidth forms duplicate the base forms.
